version: '3.8'

services:
  php:
    build: .
    container_name: symfony_php
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
      - mailhog
      - mongodb
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/symfony?serverVersion=8.0"
      MAILER_DSN: "smtp://mailhog:2525"
      APP_ENV: dev
      APP_SECRET: "24e17c47430bd2044a61c131c1cf6990"
      MONGODB_URL: "mongodb://root:root@mongodb:27017/symfony?authSource=admin"

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    platform: linux/arm64/v8
    image: arm64v8/phpmyadmin:latest
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

  mailhog:
    platform: linux/amd64
    image: mailhog/mailhog
    container_name: symfony_mailhog
    ports:
      - "2525:1025"
      - "8026:8025"

  mongodb:
    image: mongo:latest
    container_name: symfony_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: symfony
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: symfony_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/admin
    depends_on:
      - mongodb

volumes:
  db_data:
  mongodb_data:
