[PHP]
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On
error_log = /var/log/apache2/php_errors.log
memory_limit = 256M
max_execution_time = 30
upload_max_filesize = 20M
post_max_size = 20M

[Date]
date.timezone = UTC

[opcache]
opcache.enable=1
opcache.memory_consumption=256
opcache.max_accelerated_files=20000
opcache.validate_timestamps=1
opcache.revalidate_freq=0

[MongoDB]
extension=mongodb.so 